### ISSUE TITLE
Error when trying install strong-agent

### ISSUE THREAD

**Issue by nairihar** [strongloop/strong-agent#14]
Hi, I am using Node v8.11.3 and can't install strong-agent module.

<img width="838" alt="screen shot 2018-10-27 at 10 01 55 pm" src="https://user-images.githubusercontent.com/15065065/47607673-001f3580-da34-11e8-934d-15377e984c7e.png">

**Comment by bnoordhuis** [comment]
All strong-agent functionality has been migrated to https://github.com/RuntimeTools/appmetrics. It supports Node.js 8.

If you have a support contract and switching to appmetrics is not an option for you, I can look into updating strong-agent.

**Comment by nairihar** [comment]
thanks @bnoordhuis
